name: Version in jede Programm-Datei schreiben

on:
  push:
    branches: [main]

jobs:
  write-and-commit:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'Bot: Update version files')"

    permissions:
      contents: write

    steps:
      # 1. Code auschecken
      - name: Code auschecken
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. NEUER SCHRITT: Alte version.txt Dateien bereinigen
      - name: Alte version.txt Dateien löschen
        run: |
          echo "Suche und lösche alle alten version.txt Dateien..."
          # Dieser Befehl findet alle Dateien mit dem Namen 'version.txt' und löscht sie.
          # Das stellt sicher, dass keine veralteten Dateien übrig bleiben.
          find . -type f -name "version.txt" -print -delete
          echo "Bereinigung abgeschlossen."

      # 3. Versionen erstellen und in die richtigen Ordner schreiben
      - name: Versionen erstellen und schreiben
        run: |
          # --- Versionen einmalig vorbereiten ---
          VERSION=$(cat VERSION)
          COMMIT_DATE=$(git log -1 --format=%cd --date=format:%d%m%Y)
          COMMIT_HASH=$(git rev-parse --short HEAD)
          
          # Standard-Version
          QUALIFIER_DEFAULT=$(cat QUALIFIER)
          FULL_VERSION_DEFAULT="${VERSION}+${QUALIFIER_DEFAULT}.${COMMIT_DATE}.${COMMIT_HASH}"

          # Beta-Version
          FULL_VERSION_BETA="${VERSION}+BETA.${COMMIT_DATE}.${COMMIT_HASH}"

          echo "Standard-Version: ${FULL_VERSION_DEFAULT}"
          echo "Beta-Version:     ${FULL_VERSION_BETA}"

          # --- /app/ und alle Unterordner bearbeiten ---
          echo "--- Bearbeite /app und alle Unterordner ---"
          if [ -d "app" ]; then
            for dir in $(find app -type d); do
              echo "Schreibe Standard-Version in ${dir}/version.txt"
              echo "${FULL_VERSION_DEFAULT}" > "${dir}/version.txt"
            done
          else
            echo "Ordner /app nicht gefunden, überspringe."
          fi

          # --- /beta/app/ und alle Unterordner bearbeiten ---
          echo "--- Bearbeite /beta/app und alle Unterordner ---"
          if [ -d "beta/app" ]; then
            for dir in $(find beta/app -type d); do
              echo "Schreibe BETA-Version in ${dir}/version.txt"
              echo "${FULL_VERSION_BETA}" > "${dir}/version.txt"
            done
          else
            echo "Ordner /beta/app nicht gefunden, überspringe."
          fi

      # 4. Alle neuen version.txt Dateien committen
      - name: Änderungen an allen version.txt Dateien committen
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Bot: Update version files"
          file_pattern: "**/version.txt"
